# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalDataProgram.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frMain = QtWidgets.QFrame(self.centralwidget)
        self.frMain.setGeometry(QtCore.QRect(0, 0, 1381, 901))
        self.frMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frMain.setObjectName("frMain")
        self.lblTwitterUsers = QtWidgets.QLabel(self.frMain)
        self.lblTwitterUsers.setGeometry(QtCore.QRect(625, 12, 161, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.lblTwitterUsers.sizePolicy().hasHeightForWidth())
        self.lblTwitterUsers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblTwitterUsers.setFont(font)
        self.lblTwitterUsers.setWordWrap(False)
        self.lblTwitterUsers.setObjectName("lblTwitterUsers")
        self.frFreqDist = QtWidgets.QFrame(self.frMain)
        self.frFreqDist.setGeometry(QtCore.QRect(20, 320, 468, 241))
        self.frFreqDist.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frFreqDist.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frFreqDist.setObjectName("frFreqDist")
        self.lblFreqDistOptions = QtWidgets.QLabel(self.frFreqDist)
        self.lblFreqDistOptions.setGeometry(QtCore.QRect(110, 10, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lblFreqDistOptions.setFont(font)
        self.lblFreqDistOptions.setObjectName("lblFreqDistOptions")
        self.cbIncludeFreqDist = QtWidgets.QCheckBox(self.frFreqDist)
        self.cbIncludeFreqDist.setGeometry(QtCore.QRect(17, 60, 441, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbIncludeFreqDist.setFont(font)
        self.cbIncludeFreqDist.setObjectName("cbIncludeFreqDist")
        self.cbCommonWords = QtWidgets.QCheckBox(self.frFreqDist)
        self.cbCommonWords.setGeometry(QtCore.QRect(17, 98, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbCommonWords.setFont(font)
        self.cbCommonWords.setObjectName("cbCommonWords")
        self.cbIncludeFreqDistAllAccounts = QtWidgets.QCheckBox(self.frFreqDist)
        self.cbIncludeFreqDistAllAccounts.setGeometry(QtCore.QRect(17, 170, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbIncludeFreqDistAllAccounts.setFont(font)
        self.cbIncludeFreqDistAllAccounts.setObjectName("cbIncludeFreqDistAllAccounts")
        self.leCommonWords = QtWidgets.QLineEdit(self.frFreqDist)
        self.leCommonWords.setEnabled(False)
        self.leCommonWords.setGeometry(QtCore.QRect(97, 102, 73, 20))
        self.leCommonWords.setObjectName("leCommonWords")
        self.leExcludeChars = QtWidgets.QLineEdit(self.frFreqDist)
        self.leExcludeChars.setEnabled(False)
        self.leExcludeChars.setGeometry(QtCore.QRect(269, 143, 35, 20))
        self.leExcludeChars.setObjectName("leExcludeChars")
        self.cbExcludeShortWords = QtWidgets.QCheckBox(self.frFreqDist)
        self.cbExcludeShortWords.setGeometry(QtCore.QRect(17, 142, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbExcludeShortWords.setFont(font)
        self.cbExcludeShortWords.setObjectName("cbExcludeShortWords")
        self.cbExcludeShortWords.raise_()
        self.lblFreqDistOptions.raise_()
        self.cbIncludeFreqDist.raise_()
        self.cbCommonWords.raise_()
        self.cbIncludeFreqDistAllAccounts.raise_()
        self.leCommonWords.raise_()
        self.leExcludeChars.raise_()
        self.frTweetNumberOptions = QtWidgets.QFrame(self.frMain)
        self.frTweetNumberOptions.setGeometry(QtCore.QRect(940, 440, 391, 141))
        self.frTweetNumberOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frTweetNumberOptions.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frTweetNumberOptions.setLineWidth(5)
        self.frTweetNumberOptions.setObjectName("frTweetNumberOptions")
        self.leDiscardAccounts = QtWidgets.QLineEdit(self.frTweetNumberOptions)
        self.leDiscardAccounts.setEnabled(False)
        self.leDiscardAccounts.setGeometry(QtCore.QRect(240, 20, 101, 20))
        self.leDiscardAccounts.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leDiscardAccounts.setObjectName("leDiscardAccounts")
        self.cbDiscardAccounts = QtWidgets.QCheckBox(self.frTweetNumberOptions)
        self.cbDiscardAccounts.setGeometry(QtCore.QRect(20, 10, 221, 31))
        self.cbDiscardAccounts.setObjectName("cbDiscardAccounts")
        self.leMaxTweets = QtWidgets.QLineEdit(self.frTweetNumberOptions)
        self.leMaxTweets.setGeometry(QtCore.QRect(240, 60, 101, 20))
        self.leMaxTweets.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.leMaxTweets.setText("")
        self.leMaxTweets.setMaxLength(4)
        self.leMaxTweets.setPlaceholderText("")
        self.leMaxTweets.setObjectName("leMaxTweets")
        self.lblMaxTweets = QtWidgets.QLabel(self.frTweetNumberOptions)
        self.lblMaxTweets.setGeometry(QtCore.QRect(20, 60, 221, 41))
        self.lblMaxTweets.setWordWrap(True)
        self.lblMaxTweets.setObjectName("lblMaxTweets")
        self.frDateFilter = QtWidgets.QFrame(self.frMain)
        self.frDateFilter.setGeometry(QtCore.QRect(20, 86, 468, 201))
        self.frDateFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frDateFilter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frDateFilter.setLineWidth(7)
        self.frDateFilter.setObjectName("frDateFilter")
        self.lblMaxTweetWarning = QtWidgets.QLabel(self.frDateFilter)
        self.lblMaxTweetWarning.setGeometry(QtCore.QRect(20, 113, 401, 61))
        self.lblMaxTweetWarning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblMaxTweetWarning.setWordWrap(True)
        self.lblMaxTweetWarning.setObjectName("lblMaxTweetWarning")
        self.lblTweetRecent = QtWidgets.QLabel(self.frDateFilter)
        self.lblTweetRecent.setGeometry(QtCore.QRect(20, 80, 151, 16))
        self.lblTweetRecent.setObjectName("lblTweetRecent")
        self.cbFilterDate = QtWidgets.QCheckBox(self.frDateFilter)
        self.cbFilterDate.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.cbFilterDate.setObjectName("cbFilterDate")
        self.lblTweetOldest = QtWidgets.QLabel(self.frDateFilter)
        self.lblTweetOldest.setGeometry(QtCore.QRect(20, 50, 121, 16))
        self.lblTweetOldest.setObjectName("lblTweetOldest")
        self.deTweetOldest = QtWidgets.QDateEdit(self.frDateFilter)
        self.deTweetOldest.setEnabled(False)
        self.deTweetOldest.setGeometry(QtCore.QRect(170, 40, 110, 22))
        self.deTweetOldest.setCalendarPopup(True)
        self.deTweetOldest.setDate(QtCore.QDate(1994, 8, 31))
        self.deTweetOldest.setObjectName("deTweetOldest")
        self.deTweetRecent = QtWidgets.QDateEdit(self.frDateFilter)
        self.deTweetRecent.setEnabled(False)
        self.deTweetRecent.setGeometry(QtCore.QRect(170, 80, 110, 22))
        self.deTweetRecent.setCalendarPopup(True)
        self.deTweetRecent.setDate(QtCore.QDate(2017, 8, 31))
        self.deTweetRecent.setObjectName("deTweetRecent")
        self.frButtons = QtWidgets.QFrame(self.frMain)
        self.frButtons.setGeometry(QtCore.QRect(520, 460, 371, 61))
        self.frButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frButtons.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frButtons.setLineWidth(5)
        self.frButtons.setObjectName("frButtons")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frButtons)
        self.verticalLayout_2.setContentsMargins(100, 9, 100, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnStart = QtWidgets.QPushButton(self.frButtons)
        self.btnStart.setObjectName("btnStart")
        self.verticalLayout_2.addWidget(self.btnStart)
        self.lblBadDataReasons = QtWidgets.QLabel(self.frMain)
        self.lblBadDataReasons.setGeometry(QtCore.QRect(1040, 300, 211, 16))
        self.lblBadDataReasons.setObjectName("lblBadDataReasons")
        self.lblAccountInstructions = QtWidgets.QLabel(self.frMain)
        self.lblAccountInstructions.setGeometry(QtCore.QRect(531, 39, 351, 16))
        self.lblAccountInstructions.setObjectName("lblAccountInstructions")
        self.progressBar = QtWidgets.QProgressBar(self.frMain)
        self.progressBar.setGeometry(QtCore.QRect(60, 600, 1261, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lblBadAccounts = QtWidgets.QLabel(self.frMain)
        self.lblBadAccounts.setGeometry(QtCore.QRect(976, 40, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblBadAccounts.setFont(font)
        self.lblBadAccounts.setWordWrap(True)
        self.lblBadAccounts.setObjectName("lblBadAccounts")
        self.txtBadUsernames = QtWidgets.QTextEdit(self.frMain)
        self.txtBadUsernames.setGeometry(QtCore.QRect(940, 90, 381, 201))
        self.txtBadUsernames.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.txtBadUsernames.setReadOnly(False)
        self.txtBadUsernames.setObjectName("txtBadUsernames")
        self.TeTwitterUsernames = QtWidgets.QPlainTextEdit(self.frMain)
        self.TeTwitterUsernames.setGeometry(QtCore.QRect(522, 60, 371, 361))
        self.TeTwitterUsernames.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.TeTwitterUsernames.setSizeIncrement(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TeTwitterUsernames.setFont(font)
        self.TeTwitterUsernames.setObjectName("TeTwitterUsernames")
        self.lwBadDataReasons = QtWidgets.QListWidget(self.frMain)
        self.lwBadDataReasons.setGeometry(QtCore.QRect(940, 320, 381, 81))
        self.lwBadDataReasons.setObjectName("lwBadDataReasons")
        item = QtWidgets.QListWidgetItem()
        self.lwBadDataReasons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwBadDataReasons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lwBadDataReasons.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.lwBadDataReasons.addItem(item)
        self.lblTwitterUsers.raise_()
        self.frFreqDist.raise_()
        self.frTweetNumberOptions.raise_()
        self.frDateFilter.raise_()
        self.frButtons.raise_()
        self.lblBadDataReasons.raise_()
        self.lblAccountInstructions.raise_()
        self.progressBar.raise_()
        self.lblBadAccounts.raise_()
        self.txtBadUsernames.raise_()
        self.TeTwitterUsernames.raise_()
        self.lwBadDataReasons.raise_()
        self.cbDiscardAccounts.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 21))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.menuTwitter = QtWidgets.QMenu(self.menubar)
        self.menuTwitter.setObjectName("menuTwitter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Project = QtWidgets.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionTwitter_Usernames = QtWidgets.QAction(MainWindow)
        self.actionTwitter_Usernames.setObjectName("actionTwitter_Usernames")
        self.actionWord_Lists = QtWidgets.QAction(MainWindow)
        self.actionWord_Lists.setObjectName("actionWord_Lists")
        self.actionStatisical_Data = QtWidgets.QAction(MainWindow)
        self.actionStatisical_Data.setObjectName("actionStatisical_Data")
        self.actionDeveloper_Credentials = QtWidgets.QAction(MainWindow)
        self.actionDeveloper_Credentials.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionDeveloper_Credentials.setObjectName("actionDeveloper_Credentials")
        self.actionTwitter_Advanced_Search = QtWidgets.QAction(MainWindow)
        self.actionTwitter_Advanced_Search.setObjectName("actionTwitter_Advanced_Search")
        self.actionTwitter_Developer_Login = QtWidgets.QAction(MainWindow)
        self.actionTwitter_Developer_Login.setObjectName("actionTwitter_Developer_Login")
        self.actionView_Last_Frequency_Distribution = QtWidgets.QAction(MainWindow)
        self.actionView_Last_Frequency_Distribution.setObjectName("actionView_Last_Frequency_Distribution")
        self.actionContent_Analysis = QtWidgets.QAction(MainWindow)
        self.actionContent_Analysis.setObjectName("actionContent_Analysis")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuTwitter.addAction(self.actionDeveloper_Credentials)
        self.menubar.addAction(self.menuTwitter.menuAction())

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Social Searcher"))
        self.lblTwitterUsers.setText(_translate("MainWindow", "Twitter Usernames "))
        self.lblFreqDistOptions.setText(_translate("MainWindow", "Frequency Distribution Options"))
        self.cbIncludeFreqDist.setText(_translate("MainWindow", "Include frequency distributions for each individual account"))
        self.cbCommonWords.setText(_translate("MainWindow", "Find the                 most common words."))
        self.cbIncludeFreqDistAllAccounts.setText(_translate("MainWindow", "Find most common words across all accounts"))
        self.cbExcludeShortWords.setText(_translate("MainWindow", "Exclude words that are less than         characters.  "))
        self.cbDiscardAccounts.setText(_translate("MainWindow", "Discard Accounts with Tweets less than:"))
        self.lblMaxTweets.setText(_translate("MainWindow", "Max Tweets to collect per account: (3200 Max. This is the default amount if box is left empty.)"))
        self.lblMaxTweetWarning.setText(_translate("MainWindow", "*Twitter only allows mining up to 3200 of the most recent Tweets at this time. Tweets that can\'t be mined may or may not exist in the desired data range. "))
        self.lblTweetRecent.setText(_translate("MainWindow", "Most Recent Date to Look For:"))
        self.cbFilterDate.setText(_translate("MainWindow", "Filter by date"))
        self.lblTweetOldest.setText(_translate("MainWindow", "Oldest Date to Look For:"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.lblBadDataReasons.setText(_translate("MainWindow", "The most common reasons for this include:"))
        self.lblAccountInstructions.setText(_translate("MainWindow", "Please use only usernames and no URLS. The @ synbol is not necessary."))
        self.lblBadAccounts.setText(_translate("MainWindow", "Accounts that were unable to be mined:"))
        self.TeTwitterUsernames.setPlaceholderText(_translate("MainWindow", "Enter one username per line. "))
        __sortingEnabled = self.lwBadDataReasons.isSortingEnabled()
        self.lwBadDataReasons.setSortingEnabled(False)
        item = self.lwBadDataReasons.item(0)
        item.setText(_translate("MainWindow", "Misspellings"))
        item = self.lwBadDataReasons.item(1)
        item.setText(_translate("MainWindow", "Deleted or  protected accounts"))
        item = self.lwBadDataReasons.item(2)
        item.setText(_translate("MainWindow", "There were no Tweets to mine."))
        item = self.lwBadDataReasons.item(3)
        item.setText(_translate("MainWindow", "None of the user\'s Tweets satisfied the desired search criteria."))
        self.lwBadDataReasons.setSortingEnabled(__sortingEnabled)
        self.menuTwitter.setTitle(_translate("MainWindow", "Twitter Options"))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionTwitter_Usernames.setText(_translate("MainWindow", "Twitter Usernames"))
        self.actionWord_Lists.setText(_translate("MainWindow", "Word Lists"))
        self.actionStatisical_Data.setText(_translate("MainWindow", "Statisical Data"))
        self.actionDeveloper_Credentials.setText(_translate("MainWindow", "Developer Credentials"))
        self.actionTwitter_Advanced_Search.setText(_translate("MainWindow", "Twitter Advanced Search"))
        self.actionTwitter_Developer_Login.setText(_translate("MainWindow", "Twitter Developer Login"))
        self.actionView_Last_Frequency_Distribution.setText(_translate("MainWindow", "View Last Frequency Distribution"))
        self.actionContent_Analysis.setText(_translate("MainWindow", "Content Analysis"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

