# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twittercredentialswidget.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgTwitterCreds(object):
    def setupUi(self, dlgTwitterCreds):
        dlgTwitterCreds.setObjectName("dlgTwitterCreds")
        dlgTwitterCreds.resize(474, 528)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgTwitterCreds)
        self.buttonBox.setGeometry(QtCore.QRect(110, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalFrame = QtWidgets.QFrame(dlgTwitterCreds)
        self.verticalFrame.setGeometry(QtCore.QRect(15, 6, 434, 401))
        self.verticalFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalFrame.setAutoFillBackground(True)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTwitterCred = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTwitterCred.sizePolicy().hasHeightForWidth())
        self.lblTwitterCred.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTwitterCred.setFont(font)
        self.lblTwitterCred.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTwitterCred.setWordWrap(True)
        self.lblTwitterCred.setObjectName("lblTwitterCred")
        self.verticalLayout.addWidget(self.lblTwitterCred)
        self.lblConsumer = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblConsumer.setFont(font)
        self.lblConsumer.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConsumer.setObjectName("lblConsumer")
        self.verticalLayout.addWidget(self.lblConsumer)
        self.leConsumerKey = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leConsumerKey.sizePolicy().hasHeightForWidth())
        self.leConsumerKey.setSizePolicy(sizePolicy)
        self.leConsumerKey.setMinimumSize(QtCore.QSize(416, 0))
        self.leConsumerKey.setObjectName("leConsumerKey")
        self.verticalLayout.addWidget(self.leConsumerKey)
        self.lblConsumerSecret = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblConsumerSecret.setFont(font)
        self.lblConsumerSecret.setAlignment(QtCore.Qt.AlignCenter)
        self.lblConsumerSecret.setObjectName("lblConsumerSecret")
        self.verticalLayout.addWidget(self.lblConsumerSecret)
        self.leConsumerSecret = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leConsumerSecret.sizePolicy().hasHeightForWidth())
        self.leConsumerSecret.setSizePolicy(sizePolicy)
        self.leConsumerSecret.setMinimumSize(QtCore.QSize(416, 0))
        self.leConsumerSecret.setObjectName("leConsumerSecret")
        self.verticalLayout.addWidget(self.leConsumerSecret)
        self.lblAccessKey = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblAccessKey.setFont(font)
        self.lblAccessKey.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAccessKey.setObjectName("lblAccessKey")
        self.verticalLayout.addWidget(self.lblAccessKey)
        self.leAccessKey = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAccessKey.sizePolicy().hasHeightForWidth())
        self.leAccessKey.setSizePolicy(sizePolicy)
        self.leAccessKey.setMinimumSize(QtCore.QSize(416, 0))
        self.leAccessKey.setObjectName("leAccessKey")
        self.verticalLayout.addWidget(self.leAccessKey)
        self.lblAccessSecret = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblAccessSecret.setFont(font)
        self.lblAccessSecret.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAccessSecret.setObjectName("lblAccessSecret")
        self.verticalLayout.addWidget(self.lblAccessSecret)
        self.leAccessSecret = QtWidgets.QLineEdit(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leAccessSecret.sizePolicy().hasHeightForWidth())
        self.leAccessSecret.setSizePolicy(sizePolicy)
        self.leAccessSecret.setMinimumSize(QtCore.QSize(416, 0))
        self.leAccessSecret.setObjectName("leAccessSecret")
        self.verticalLayout.addWidget(self.leAccessSecret)
        self.btnSave = QtWidgets.QPushButton(dlgTwitterCreds)
        self.btnSave.setGeometry(QtCore.QRect(65, 410, 100, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSave.sizePolicy().hasHeightForWidth())
        self.btnSave.setSizePolicy(sizePolicy)
        self.btnSave.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSave.setObjectName("btnSave")
        self.btnSaveSetDefault = QtWidgets.QPushButton(dlgTwitterCreds)
        self.btnSaveSetDefault.setGeometry(QtCore.QRect(215, 410, 201, 23))
        self.btnSaveSetDefault.setObjectName("btnSaveSetDefault")

        self.retranslateUi(dlgTwitterCreds)
        self.buttonBox.accepted.connect(dlgTwitterCreds.accept)
        self.buttonBox.rejected.connect(dlgTwitterCreds.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgTwitterCreds)

    def retranslateUi(self, dlgTwitterCreds):
        _translate = QtCore.QCoreApplication.translate
        dlgTwitterCreds.setWindowTitle(_translate("dlgTwitterCreds", "Dialog"))
        self.lblTwitterCred.setText(_translate("dlgTwitterCreds", "Enter your Twitter Developer credentials to authorize the data miner. Click save to verify or you may click save and set as default if they are to stay the same each time this program starts."))
        self.lblConsumer.setText(_translate("dlgTwitterCreds", "Consumer Key"))
        self.lblConsumerSecret.setText(_translate("dlgTwitterCreds", "Consumer Secret"))
        self.lblAccessKey.setText(_translate("dlgTwitterCreds", "Access Key"))
        self.lblAccessSecret.setText(_translate("dlgTwitterCreds", "Access Secret"))
        self.btnSave.setText(_translate("dlgTwitterCreds", "Save"))
        self.btnSaveSetDefault.setText(_translate("dlgTwitterCreds", "Save and Set as Default"))

